---
- name:                             "Init: Get Azure CLI Version"
  ansible.builtin.command:
    cmd:                            az version --query '"azure-cli"' --output tsv
  register:                         azure_cli_version
  changed_when:                     false

- name:                             "Init: Authenticate With Client ID (az cli >= 2.61)"
  ansible.builtin.command:
    cmd:                            >-
                                    az login --identity
                                    {% if user_assigned_identity_client_id | default('', true) | length > 0
                                    and user_assigned_identity_client_id != '00000000-0000-0000-0000-000000000000' %}
                                    --client-id {{ user_assigned_identity_client_id }}
                                    {% endif %}
  changed_when:                     false
  when:                             azure_cli_version.stdout is version('2.61', '>=')

- name:                             "Init: Authenticate With Username (az cli < 2.61)"
  ansible.builtin.command:
    cmd:                            >-
                                    az login --identity
                                    {% if user_assigned_identity_client_id | default('', true) | length > 0
                                    and user_assigned_identity_client_id != '00000000-0000-0000-0000-000000000000' %}
                                    --username {{ user_assigned_identity_client_id }}
                                    {% endif %}
  changed_when:                     false
  when:                             azure_cli_version.stdout is version('2.61', '<')
