# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------|
# |            Pre Validation Tasks for HANA DB Tests                         |
# /*---------------------------------------------------------------------------|

- name:                             "Pre Validation: HANA DB Nodes"
  when:                             node_tier == "hana"
  block:
    - name:                         "Pre Validation: Remove any location_constraints"
      become:                       true
      location_constraints:
        action:                     "remove"
      register:                     location_constraints_results

    - name:                         "Pre Validation: Get SAPHanaSR Provider"
      become:                       true
      become_user:                  "{{ db_sid | lower }}"
      ansible.builtin.command:      "/usr/sbin/SAPHanaSR-manageProvider --show --provider=sushanasr"
      register:                     hanasr_command_output
      changed_when:                 false

    - name:                         "Pre Validation: Set SAPHanaSR Provider"
      when:                         hanasr_command_output.stdout != 0
      ansible.builtin.set_fact:
        saphanasr_provider:         "SAPHanaSR"
    
    - name:                         "Pre Validation: Set SAPHanaSR-angi Provider"
      when:                         hanasr_command_output.stdout == ""
      ansible.builtin.set_fact:
        saphanasr_provider:         "SAPHanaSR-angi"

    - name:                         "Pre Validation: Validate HANA DB cluster status on primary node"
      become:                       true
      get_cluster_status_db:
        operation_step:             "pre_failover"
        database_sid:               "{{ db_sid | lower }}"
        saphanasr_provider:         "{{ saphanasr_provider }}"
      register:                     cluster_status_pre

    - name:                         "Pre Validation: CleanUp any failed resource"
      become:                       true
      ansible.builtin.command:      crm_resource --cleanup
      ignore_errors:                true
      register:                     cleanup_failed_resource_pre
      timeout:                      "{{ default_timeout }}"
      retries:                      3
      until:                        cleanup_failed_resource_pre.rc == 0
      changed_when:                 cleanup_failed_resource_pre.rc == 0
      failed_when:                  cleanup_failed_resource_pre.rc != 0

    - name:                         "Pre Validation: Set default pre Validation status as false"
      ansible.builtin.set_fact:
        pre_validations_status:     "FAILED"

    - name:                         "Pre Validation: Set pre Validation status"
      when:
                                    - cluster_status_pre is defined
                                    - cluster_status_pre.primary_node != "" and
                                      cluster_status_pre.secondary_node != ""
                                    - cluster_status_pre.pacemaker_status == "running"
      ansible.builtin.set_fact:
        pre_validations_status:     "PASSED"
