# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------|
# |            Pre Validations Tasks for HANA DB Tests                         |
# /*---------------------------------------------------------------------------|

- name:                             "Pre Validations: HANA DB Nodes"
  when:                             node_tier == "hana"
  block:
    - name:                         "Pre Validations: Remove any location_constraints"
      become:                       true
      location_constraints:
        action:                     "remove"
        ansible_os_family:          "{{ ansible_os_family | upper}}"
      register:                     location_constraints_results

    - name:                         "Pre Validations: Validate HANA DB cluster status on primary node"
      become:                       true
      get_cluster_status:
        operation_step:             "pre_failover"
        database_sid:               "{{ db_sid | lower }}"
      register:                     cluster_status_pre

    - name:                         "Pre Validations: Check if the AUTOMATED_REGISTER parameter
                                    is set to true"
      become:                       true
      ansible.builtin.shell:        "{{ commands
                                    | selectattr('name', 'equalto', 'automated_register_cmd')
                                    | map(attribute=(ansible_os_family | upper)) | first }}"
      register:                     automated_register
      changed_when:                 false
      when:                         cluster_status_pre is defined

    - name:                         "Pre Validations: CleanUp any failed resource"
      become:                       true
      ansible.builtin.command:      crm_resource --cleanup
      ignore_errors:                true
      register:                     cleanup_failed_resource_pre
      timeout:                      60
      retries:                      3
      until:                        cleanup_failed_resource_pre.rc == 0
      changed_when:                 cleanup_failed_resource_pre.rc == 0
      failed_when:                  cleanup_failed_resource_pre.rc != 0

    - name:                         "Pre Validations: Set default pre validations status as false"
      ansible.builtin.set_fact:
        pre_validations_status:     "FAILED"

    - name:                         "Pre Validations: Set pre validations status"
      when:
                                    - cluster_status_pre is defined
                                    - cluster_status_pre.primary_node != "" and cluster_status_pre.secondary_node != ""
                                    - cluster_status_pre.pacemaker_status == "running"
      ansible.builtin.set_fact:
        pre_validations_status:     "PASSED"
