# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

################################################################################
#                Rescue tasks for the test cases                               #
################################################################################

- name:                         "Read var log messages by importing role"
  ansible.builtin.include_tasks: "roles/misc/tasks/var-log-messages.yml"

- name:                         "Post Validations: Set test case status"
  ansible.builtin.set_fact:
    test_case_name:             "{{ item.name }}: {{ virtual_host }}"
    test_case_hostname:         "{{ virtual_host }}"
    test_case_description:      "{{ item.description }}"
    test_case_status:           "FAILED"
    test_case_message:          "{{ ansible_failed_result }}"
    test_case_details:          "{{ ansible_failed_result }}"
    test_case_var_log_messages: "{{ var_log_messages_output.filtered_logs }}"

- name:                         "Post Telemetry Data"
  ansible.builtin.include_tasks: "roles/misc/tasks/post-telemetry-data.yml"
  run_once:                     true