# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

################################################################################
#                Rescue tasks for the test cases                               #
################################################################################

- name:                                 "Read var log messages by importing role"
  ansible.builtin.include_tasks:        "roles/misc/tasks/var-log-messages.yml"

- name:                                 "Post Validations: HA cluster status after test execution"
  block:
    - name:                             "Set node variables based on cluster status"
      ansible.builtin.set_fact:
        first_node:                     "{{ cluster_status_pre.primary_node | default(cluster_status_pre.ascs_node) }}"
        second_node:                    "{{ cluster_status_pre.secondary_node | default(cluster_status_pre.ers_node) }}"

    - name:                             "Combine logs from both Nodes"
      ansible.builtin.set_fact:
        combined_logs: >-
                                        {{
                                          (
                                            hostvars[first_node]['var_log_messages_output'].filtered_logs
                                            | default([])
                                          )
                                          +
                                          (
                                            hostvars[second_node]['var_log_messages_output'].filtered_logs
                                            | default([])
                                          )
                                        }}

    - name:                             "Post Validations: Rescure operation set test case status"
      delegate_to:                      localhost
      ansible.builtin.set_fact:
        test_case_name:                 "{{ item.name }}: {{ test_execution_hostname }}"
        test_case_hostname:             "{{ virtual_host }}"
        test_case_description:          "{{ item.description }}"
        test_case_status:               "FAILED"
        test_case_message:              "{{ ansible_failed_result }}"
        test_case_details:              "{{ ansible_failed_result }}"
        test_case_var_log_messages:     "{{ combined_logs }}"

- name:                                 "Post Telemetry Data"
  ansible.builtin.include_tasks:        "roles/misc/tasks/post-telemetry-data.yml"
  run_once:                             true
