# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

################################################################################################
#                      Read the log file /var/log/messages for given time period               #
################################################################################################

- name:                                 Read the log file /var/log/messages for given time period
  block:
    - name:                             Read the log file /var/log/messages for given time period
      become:                           true
      log_parser:
        start_time:                     "{{ test_execution_start | default(test_case_start_time_epoch) }}"
        end_time:                       "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
        ansible_os_family:              "{{ ansible_os_family | upper }}"
      register:                         var_log_messages_output

- name:                                 Combine log results from both nodes
  run_once:                             true
  delegate_to:                          localhost
  ansible.builtin.set_fact:
    combined_var_log_messages:          "{{ combined_var_log_messages | default([]) + [node.var_log_messages_output.filtered_logs] }}"
  loop:                                 "{{ groups['all'] }}"
  loop_control:
    loop_var:                           node
  when:                                 node.var_log_messages_output is defined
