# This file is used by GitHub Dependabot to manage dependencies in the project.

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
