[tool.black]
line_length = 100

[tool.pylint.main]
load-plugins = ["pylint.extensions.docparams"]

[tool.pylint.basic]
argument-naming-style = "snake_case"
attr-naming-style = "snake_case"
class-naming-style = "PascalCase"
function-naming-style = "snake_case"
variable-naming-style = "snake_case"
module-naming-style = "snake_case"
bad-names = ["foo", "bar", "baz", "toto", "tutu", "tata"]
docstring-min-length = 10

[tool.pylint.format]
max-line-length = 100
max-module-lines = 1000

[tool.pylint.docs]
docstring-style = "sphinx"
default-docstring-type = "sphinx"
accept-no-param-doc = false
accept-no-raise-doc = false
accept-no-return-doc = false
accept-no-yields-doc = false

[tool.pylint."messages control"]
enable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "wrong-exception-operation",
    "wrong-spelling-in-comment",
    "wrong-spelling-in-docstring",
    "missing-any-param-doc",
    "missing-format-attribute",
    "missing-kwoa",
    "missing-param-doc",
    "missing-parentheses-for-call-in-test",
    "missing-raises-doc",
    "missing-return-doc",
    "missing-return-type-doc",
    "missing-timeout",
    "missing-type-doc",
    "missing-yield-doc",
    "missing-yield-type-doc",
    "trailing-newlines",
    "trailing-whitespace",
]
disable = [
    "C0199",  # empty-first-line-docstring
    "W0702",  # bare-except
    "W0703",  # broad-except
    "W4901",  # global-statement
    "W0108",  # lambda
    "W0622",  # redefined-builtin id
    "E0015",
    "E0401",  # import-error
    "E0611",  # no-name-in-module
]

[tool.pylint.design]
max-args = 5

[tool.pylint.variables]
init-import = false
dummy-variables-rgx = "_.*|dummy"

[tool.pylint.refactoring]
max-nested-blocks = 3

[tool.pylint.errors]
enable = [
    "E1101",
    "W0611",
]

[tool.pylint.tests]
disable = [
    "W0702",  # bare-except
    "W0703",  # broad-except
    "W4901",  # global-statement
    "R0902",  # too-many-instance-attributes
    "R0903",  # too-few-public-methods
    "R1702",  # too-many-nested-blocks
    "R0801",  # duplicate-code
    "W0108",  # lambda
    "E0401",  # import-error
    "W0613",  # unused-argument
    "W0212",  # protected-access
    "W0107",  # unnecessary-pass
    "C0103"  # invalid-name
]
