# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Description: This file contains the expected configuration for the pacemaker cluster. The values
# are based on Microsoft's best practices and are subject to change based on the customer's requirements.

CRM_CONFIG_DEFAULTS:
  cluster-infrastructure:             corosync
  have-watchdog:                      'true'
  priority-fencing-delay:             '30'
  stonith-action:                     reboot
  stonith-enabled:                    'true'
  stonith-timeout:                    144s

OP_DEFAULTS:
  record-pending:                     'true'
  timeout:                            '600'

RSC_DEFAULTS:
  migration-threshold:                '5000'
  priority:                           '1'
  resource-stickiness:                '1000'

# <constraints>
#   <rsc_colocation id="col_saphana_ip_HDB_HDB00" score="4000" rsc="g_ip_HDB_HDB00" rsc-role="Started" with-rsc="msl_SAPHana_HDB_HDB00" with-rsc-role="Master"/>
#   <rsc_order id="ord_SAPHana_HDB_HDB00" kind="Optional" first="cln_SAPHanaTopology_HDB_HDB00" then="msl_SAPHana_HDB_HDB00"/>
# </constraints>
CONSTRAINTS:
  rsc_colocation:
    score:                            "4000"
    rsc-role:                         "Started"
    with-rsc-role:                    "Master"

  rsc_order:
    kind:                             "Optional"



VALID_CONFIGS:
  RHEL:
    '8.4': {}
    '9.0':
      migration-threshold:            '4000'
      priority:                       '2'
      priority-fencing-delay:         '40'
      record-pending:                 'false'
      resource-stickiness:            '1500'
      stonith-action:                 'off'
      stonith-timeout:                120s
      timeout:                        '700'
  SLES:
    '15.2': {}
    '15.3':
      migration-threshold:            '4500'
      priority:                       '3'
      priority-fencing-delay:         '25'
      record-pending:                 'false'
      resource-stickiness:            '1200'
      stonith-action:                 'off'
      stonith-enabled:                'false'
      stonith-timeout:                100s
      timeout:                        '650'

RESOURCE_DEFAULTS:
  stonith:
    instance_attributes:
      pcmk_delay_max:                     "30s"
      pcmk_monitor_retries:               "4"
      pcmk_action_limit:                  "3"
      pcmk_reboot_timeout:                "900"
      power_timeout:                      "240"
    monitor:
      interval:                           "3600"
      timeout:                            "120"

  topology:
    meta_attributes:
      clone-node-max:                   "1"
      target-role:                      "Started"
      interleave:                       "true"
    operations:
      monitor:
        interval:                       "10"
        timeout:                        "600"
      start:
        interval:                       "0"
        timeout:                        "600"
      stop:
        interval:                       "0"
        timeout:                        "300"

  hana:
    meta_attributes:
      notify:                           "true"
      clone-max:                        "2"
      clone-node-max:                   "1"
      target-role:                      "Started"
      interleave:                       "true"
      priority:                         "100"
    instance_attributes:
      PREFER_SITE_TAKEOVER:             "true"
      DUPLICATE_PRIMARY_TIMEOUT:        "7200"
      AUTOMATED_REGISTER:               "true"
    operations:
      start:
        interval:                       "0"
        timeout:                        "3600"
      stop:
        interval:                       "0"
        timeout:                        "3600"
      promote:
        interval:                       "0"
        timeout:                        "3600"
      monitor:
        interval:                       "60"
        timeout:                        "700"

  ipaddr:
    meta_attributes:
      target-role:                      "Started"
    operations:
      monitor:
        interval:                       "10s"
        timeout:                        "20s"

  filesystem:
    meta_attributes:
      clone-node-max:                   "1"
      interleave:                       "true"
    operations:
      monitor:
        interval:                       "120"
        timeout:                        "120"
      start:
        interval:                       "0"
        timeout:                        "120"
      stop:
        interval:                       "0"
        timeout:                        "120"

OS_PARAMETERS:
  DEFAULTS:
    sysctl:
      net.ipv4.tcp_timestamps:            "0"
      vm.swappiness:                      "10"
    corosync-cmapctl:
      runtime.config.totem.token:         "30000"
      runtime.config.totem.consensus:     "36000"
