# /*---------------------------------------------------------------------------
# |                                                                            |
# |                          Manual resource migration                         |
# |                                                                            |
# +--------------------------------------------------------------------------*/
- name:                                   "Test Setup Tasks"
  ansible.builtin.include_tasks:          "roles/misc/tasks/test-case-setup.yml"

- name:                                   "Pre Validations: DB Nodes"
  become:                                 true
  when:
    - "'db' in inventory_hostname"
  block:
    - name:                               "Pre Validations: Remove any location_constraints"
      location_constraints:
        action:                           "remove"
      register:                           location_constraints_results

    - name:                               "Pre Validations: Validate HANA DB cluster status before migrating the HANA DB"
      crm_cluster_status:
          operation_step:                 "pre_failover"
      register:                           crm_cluster_status_results_pre
      failed_when:                        crm_cluster_status_results_pre.primary_node == None or crm_cluster_status_results_pre.secondary_node == None

    - name:                               "Pre Validations on the primary node"
      when:
        - ansible_hostname == crm_cluster_status_results_pre.primary_node
      block:
        - name:                           "Pre Validations: Check if the AUTOMATED_REGISTER parameter is set to true"
          ansible.builtin.shell:
            cmd: |
                                          set -o pipefail
                                          crm configure show | grep AUTOMATED_REGISTER=true | awk '{print $6}'
            executable:                   /bin/bash
          register:                       automated_register
          changed_when:                   false
          when:
            - crm_cluster_status_results_pre is defined

        - name:                            "Pre Validations: CleanUp any failed resource"
          ansible.builtin.command:         crm resource cleanup
          register:                        cleanup_failed_resource_pre
          changed_when:                    cleanup_failed_resource_pre.rc == 0

    - name:                                "Test Execution: Crash the primary node."
      when:
        - ansible_hostname == crm_cluster_status_results_pre.primary_node
        - crm_cluster_status_results_pre.status == "running"
        - crm_cluster_status_results_pre is defined
      block:
        - name:                             "Test Execution: Move the resource to the targeted node"
          ansible.builtin.command: |
            crm resource move msl_SAPHana_{{ db_sid | upper }}_HDB{{ db_instance_number }} \
            {{ crm_cluster_status_results_pre.secondary_node }} force
          register:                         hana_db_resource_migration
          failed_when:                      hana_db_resource_migration.rc != 0
          changed_when:                     hana_db_resource_migration.rc == 0

        - name:                             "Test Execution: Pause for migration to complete"
          ansible.builtin.wait_for:
            timeout:                        300
          when:
            - automated_register.stdout != ""

        - name:                             "Test Execution: Register Failed Resource"
          become:                           true
          become_user:                      "{{ db_sid | lower }}adm"
          when:
            - crm_cluster_status_results_pre is defined
            - automated_register.stdout == ""
          ansible.builtin.command: |
            hdbnsutil -sr_register \
            --remoteHost={{ crm_cluster_status_results_pre.secondary_node }} \
            --remoteInstance={{ db_instance_number }} \
            --replicationMode=sync --name=SITEB
          register:                         hana_db_register_failed_resource
          changed_when:                     hana_db_register_failed_resource.rc == 0

        - name:                              "Test Execution: Remove any location_constraints"
          location_constraints:
            action:                          "remove"
          register:                          location_constraints_results

    - name:                                 "Post Validations: HA cluster status after migrating the HANA DB"
      when:
        - ansible_hostname == crm_cluster_status_results_pre.primary_node
        - crm_cluster_status_results_pre is defined
      block:
        - name:                              "Post Validations: CleanUp any failed resource"
          ansible.builtin.command:           crm resource cleanup rsc_SAPHana_{{ db_sid | upper }}_HDB{{ db_instance_number }}
          register:                          cleanup_failed_resource_post
          changed_when:                      cleanup_failed_resource_post.rc == 0

        - name:                              "Post Validations: Validate HANA DB cluster status after migrating the HANA DB"
          crm_cluster_status:
            operation_step:                  "post_failover"
          register:                          crm_cluster_status_results_post
          failed_when:                       crm_cluster_status_results_post.primary_node == None or crm_cluster_status_results_post.secondary_node == None

        - name:                              "Post Validations: Set test case status"
          ansible.builtin.set_fact:
            test_case_status:                "PASSED"

      rescue:
        - name:                              "Post Validations: Set test case status"
          ansible.builtin.set_fact:
            test_case_status:                "FAILED"

- name:                                      "Post Telemetry Data"
  ansible.builtin.include_tasks:             "roles/misc/tasks/post-telemetry-data.yml"
  vars:
    test_case_message:                       "Old primary instance is: {{ crm_cluster_status_results_pre.primary_node }} \
                                              New primary instance is: {{ crm_cluster_status_results_post.primary_node }} \
                                              Old secondary instance is: {{ crm_cluster_status_results_pre.secondary_node }} \
                                              New secondary instance is: {{ crm_cluster_status_results_post.secondary_node }}"
    test_case_details:                        {
                                                "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                                "Pre Validations: Validate HANA DB cluster status": "{{ crm_cluster_status_results_pre }}",
                                                "Pre Validations: Check if the AUTOMATED_REGISTER": "{{ automated_register }}",
                                                "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre }}",
                                                "Test Execution: Move the resource to the targeted node": "{{ hana_db_resource_migration }}",
                                                "Post Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_post }}",
                                                "Post Validations: Validate HANA DB cluster status": "{{ crm_cluster_status_results_post }}"
                                              }
  run_once:                                   true
