---
# User-defined variables
telemetry_table_name:       SAP_AUTOMATION_QA
test_group_name:            HA_DB_HANA_SLES
telemetry_data_destination: loganalytics

# Azure Log Analytics LAWS variables
laws_shared_key:            null
laws_workspace_id:          null

# Azure Data Explorer (ADX) variables
adx_database_name:          null
adx_cluster_fqdn:           null
adx_client_id:              null

# DONOT CHANGE
# Test group variables
# Description: This contains the test groups and test cases that will be executed by the quality assurance playbook

test_groups:
  - name:                           HA_DB_HANA_SLES
    test_cases:
      - name:                       HA Parameters Validation
        task_name:                  ha-config
        description:                This validates the HA configuration

      # - name:                       HA Functional Test- Resource Migration
      #   task_name:                  resource-migration
      #   description:                This runs a functional test for resource migration

      # - name:                       HA Functional Test- Primary Node Crash
      #   task_name:                  primary-node-crash
      #   description:                This runs a functional test for primary node crash

  - name: HA_SCS_SLES
    test_cases:
      - name: ha-config
        description: This validates the HA configuration
