---
# DONOT CHANGE
# Test group variables
# Description: This contains the test groups and test cases that will be executed by the quality assurance playbook

# Map of functional type name and actual values
sap_functional_test_type_map:
  - name:                   "DatabaseHighAvailability"
    value:                  HA_DB
  - name:                   "CentralServicesHighAvailability"
    value:                  HA_SCS

# Test group variables
test_groups:
  - name:                           HA_DB_HANA_SUSE
    test_cases:
      - name:                       HA Parameters Validation
        task_name:                  ha-config
        description:                This validates the HA configuration

      - name:                       HA Functional Test- Primary Node Crash
        task_name:                  primary-node-crash
        description:                This runs a functional test for primary node crash

      - name:                       HA Functional Test- Resource Migration
        task_name:                  resource-migration
        description:                This runs a functional test for resource migration

  - name:                           HA_DB_HANA_REDHAT
    test_cases:
      - name:                       HA Parameters Validation
        task_name:                  ha-config
        description:                This validates the HA configuration

      - name:                       HA Functional Test- Resource Migration
        task_name:                  resource-migration
        description:                This runs a functional test for resource migration

      - name:                       HA Functional Test- Primary Node Crash
        task_name:                  primary-node-crash
        description:                This runs a functional test for primary node crash

  - name: HA_SCS_SUSE
    test_cases:
      - name: ha-config
        description: This validates the HA configuration
  
  - name: HA_SCS_REDHAT
    test_cases:
      - name: ha-config
        description: This validates the HA configuration
