# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------
# |               Kill SBD Inquisitor                                         |
# +--------------------------------------------------------------------------*/
- name:                             "Test Setup Tasks"
  ansible.builtin.include_tasks:    "roles/misc/tasks/test-case-setup.yml"
  run_once:                         true

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                             "Pre Validations: HANA DB Nodes"
  ansible.builtin.include_tasks:    "roles/misc/tasks/pre-validations.yml"
  run_once:                         true

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/
- name:                             "Test Execution: SBD Inquisitor kill"
  become:                           true
  when:
    - node_tier == "hana"
    - cluster_status_pre.primary_node != "" and cluster_status_pre.secondary_node != ""
    - cluster_status_pre.status == "running"
    - cluster_status_pre is defined
  block:
    - name:                         "Test Execution: SBD Inquisitor kill init"
      when:
        - ansible_hostname == cluster_status_pre.primary_node
      block:
        - name:                     "Test Execution: Start timer"
          ansible.builtin.set_fact:
            test_execution_start:   "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

        - name:                     "Test Execution:  Find the port of inquisitor process"
          become:                   true
          ansible.builtin.shell:    "pgrep -f 'sbd: inquisitor' | head -n 1"
          register:                 inquisitor_port
          failed_when:              inquisitor_port.rc != 0

        - name:                     "Test Execution: Kill the inquisitor process"
          become:                   true
          ansible.builtin.shell:    "kill -9 {{ inquisitor_port.stdout }}"
          async:                    1
          poll:                     0
          register:                 inquisitor_kill
          failed_when:              inquisitor_kill.rc != 0

    - name:                         "Test Execution: Wait for the failover to happen"
      when:
        - ansible_hostname == cluster_status_pre.secondary_node
      block:
        - name:                     "Test Execution: Validate HANA DB cluster status during stop operation."
          when:                     automated_register.stdout != ""
          get_cluster_status:
            operation_step:         "test_execution"
            database_sid:           "{{ db_sid | lower }}"
          retries:                  40
          delay:                    30
          register:                 cluster_status_test_execution
          until: |
                                    - cluster_status_test_execution.primary_node == cluster_status_pre.secondary_node
                                    - cluster_status_test_execution.secondary_node == cluster_status_pre.primary_node

    - name:                         "Test Execution: SBD Inquisitor kill manual fail over"
      when:
        - ansible_hostname == cluster_status_pre.primary_node
      block:
        - name:                     "Test Execution: Register Failed Resource"
          become:                   true
          become_user:              "{{ db_sid | lower }}adm"
          when:
            - automated_register.stdout == ""
          ansible.builtin.command: |
                                    hdbnsutil -sr_register \
                                    --remoteHost={{ cluster_status_pre.secondary_node }} \
                                    --remoteInstance={{ db_instance_number }} \
                                    --replicationMode=sync --name=SITEB
          register:                 hana_db_register_failed_resource
          changed_when:             hana_db_register_failed_resource.rc == 0

        - name:                     "Test Execution: Stop timer"
          ansible.builtin.set_fact:
            test_execution_end:     "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

        - name:                     "Set test case message and details"
          ansible.builtin.set_fact:
            test_case_message_from_test_case: "Old primary: {{ cluster_status_pre.primary_node }} \
                                      New primary: {{ cluster_status_test_execution.primary_node }} \
                                      Old secondary: {{ cluster_status_pre.secondary_node }} \
                                      New secondary: {{ cluster_status_test_execution.secondary_node }}"
            test_case_details_from_test_case: {
                                      "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                      "Pre Validations: Validate HANA DB cluster status": "{{ cluster_status_pre }}",
                                      "Pre Validations: Check if the AUTOMATED_REGISTER": "{{ automated_register }}",
                                      "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre }}",
                                      "Test Execution: Kill inquisitor results": "{{ inquisitor_kill }}",
                                      "Post Validations: Validate HANA DB cluster status": "{{ cluster_status_test_execution }}",
                                    }
# /*---------------------------------------------------------------------------
# |                          Post Validations                                 |
# +--------------------------------------------------------------------------*/
    - name:                         "Post Validations Tasks"
      ansible.builtin.include_tasks: "roles/misc/tasks/post-validations.yml"

  rescue:
    - name:                         "Rescue operation"
      ansible.builtin.include_tasks: "roles/misc/tasks/rescue.yml"
