# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------
# |                          Manual ASCS Migration                             |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup Tasks"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                                 "Pre Validations: Get initial cluster status"
  become:                               true
  ansible.builtin.command:              crm_mon -1 -o
  register:                             cluster_status_pre
  changed_when:                         false

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Execution: Manual ASCS Migration"
  become:                               true
  when:                                 node_tier == "scs"
  block:
    - name:                             "Test Execution: Start timer"
      ansible.builtin.set_fact:
        test_execution_start:           "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

    - name:                             "Test Execution: Get current ASCS node"
      ansible.builtin.shell: |
                                        set -o pipefail
                                        crm resource status rsc_sap_{{ sap_sid }}_ASCS{{ scs_instance_number }} | \
                                        grep Started | awk '{print $4}'
      register:                         current_ascs_node
      changed_when:                     false

    - name:                             "Test Execution: Move ASCS resource to other node"
      when:                             ansible_hostname == current_ascs_node.stdout
      block:
        - name:                         "Test Execution: Get target node for migration"
          ansible.builtin.set_fact:
            target_node:                "{{ groups[sap_sid ~ '_SCS'] | difference([current_ascs_node.stdout]) | first }}"

        - name:                         "Test Execution: Migrate ASCS resource"
          ansible.builtin.command:      "crm resource move rsc_sap_{{ sap_sid }}_ASCS{{ scs_instance_number }} {{ target_node }}"
          register:                     migration_result

        - name:                         "Test Execution: Wait for migration"
          ansible.builtin.command:      "crm_mon -1"
          register:                     migration_status
          until:                        "'Started {{ target_node }}' in migration_status.stdout"
          retries:                      30
          delay:                        10

        - name:                         "Test Execution: Clear resource constraints"
          ansible.builtin.command:      "crm resource clear rsc_sap_{{ sap_sid }}_ASCS{{ scs_instance_number }}"
          register:                     clear_result

    - name:                             "Test Execution: Stop timer"
      ansible.builtin.set_fact:
        test_execution_end:             "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

    - name:                             "Test Execution: Verify final cluster status"
      ansible.builtin.command:          crm_mon -1 -o
      register:                         cluster_status_post
      changed_when:                     false

    - name:                             "Set test case message and details"
      ansible.builtin.set_fact:
        test_case_message_from_test_case: "ASCS resource successfully migrated from {{ current_ascs_node.stdout }} to {{ target_node }}"
        test_case_details_from_test_case: {
                                        "Pre Validations Status": "{{ cluster_status_pre.stdout }}",
                                        "Migration Result": "{{ migration_result }}",
                                        "Clear Constraints Result": "{{ clear_result }}",
                                        "Post Migration Status": "{{ cluster_status_post.stdout }}"
                                        }

# /*---------------------------------------------------------------------------
# |                          Post Validations                                 |
# +--------------------------------------------------------------------------*/
    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"

  rescue:
    - name:                             "Rescue operation"
      ansible.builtin.include_tasks:    "roles/misc/tasks/rescue.yml"
