# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------
# |                          Kill Message Server Process                       |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup Tasks"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                                 "Pre Validations: Get initial cluster status"
  become:                               true
  ansible.builtin.command:              crm_mon -1 -o
  register:                             cluster_status_pre
  changed_when:                         false

- name:                                 "Pre Validations: Get current ASCS node"
  ansible.builtin.shell: |
                                        set -o pipefail
                                        crm resource status rsc_sap_{{ sap_sid }}_ASCS{{ scs_instance_number }} | \
                                        grep Started | awk '{print $4}'
  register:                             current_ascs_node
  changed_when:                         false

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Execution: Kill Message Server Process"
  become:                               true
  when:                                 node_tier == "scs"
  block:
    - name:                             "Test Execution: Start timer"
      ansible.builtin.set_fact:
        test_execution_start:           "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

    - name:                             "Test Execution: Kill message server on ASCS node"
      when:                             ansible_hostname == current_ascs_node.stdout
      block:
        - name:                         "Test Execution: Find message server PID"
          ansible.builtin.shell:        "pgrep -f 'ms.sap{{ sap_sid }}'"
          register:                     ms_pid
          changed_when:                 false

        - name:                         "Test Execution: Kill message server process"
          ansible.builtin.command:      "kill -9 {{ ms_pid.stdout }}"
          register:                     kill_result
          when:                         ms_pid.stdout != ""

        - name:                         "Test Execution: Wait for process restart"
          ansible.builtin.wait_for:
            timeout:                    30

        - name:                         "Test Execution: Verify message server restart"
          ansible.builtin.shell:        "pgrep -f 'ms.sap{{ sap_sid }}'"
          register:                     new_ms_pid
          changed_when:                 false
          retries:                      6
          delay:                        10
          until:                        new_ms_pid.stdout != "" and new_ms_pid.stdout != ms_pid.stdout

    - name:                             "Test Execution: Stop timer"
      ansible.builtin.set_fact:
        test_execution_end:             "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

    - name:                             "Test Execution: Get final cluster status"
      ansible.builtin.command:          crm_mon -1 -o
      register:                         cluster_status_post
      changed_when:                     false

    - name:                             "Set test case message and details"
      ansible.builtin.set_fact:
        test_case_message_from_test_case: "Message server process killed and auto-recovered on {{ current_ascs_node.stdout }}"
        test_case_details_from_test_case: {
                                        "Pre Validations Status": "{{ cluster_status_pre.stdout }}",
                                        "Original PID": "{{ ms_pid.stdout }}",
                                        "Kill Result": "{{ kill_result }}",
                                        "New PID": "{{ new_ms_pid.stdout }}",
                                        "Post Status": "{{ cluster_status_post.stdout }}"
                                        }

# /*---------------------------------------------------------------------------
# |                          Post Validations                                 |
# +--------------------------------------------------------------------------*/
    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"

  rescue:
    - name:                             "Rescue operation"
      ansible.builtin.include_tasks:    "roles/misc/tasks/rescue.yml"
