# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------
# |                    Kill Enqueue Replication Server Process                |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup Tasks"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                                 "Pre Validations: Get initial cluster status"
  become:                               true
  ansible.builtin.command:              crm_mon -1 -o
  register:                             cluster_status_pre
  changed_when:                         false

- name:                                 "Pre Validations: Get current ERS node"
  ansible.builtin.shell: |
                                        set -o pipefail
                                        crm resource status rsc_sap_{{ sap_sid }}_ERS{{ ers_instance_number }} | \
                                        grep Started | awk '{print $4}'
  register:                             current_ers_node
  changed_when:                         false

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Execution: Kill Enqueue Replication Process"
  become:                               true
  when:                                 node_tier == "ers"
  block:
    - name:                             "Test Execution: Start timer"
      ansible.builtin.set_fact:
        test_execution_start:           "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

    - name:                             "Test Execution: Kill replication server on ERS node"
      when:                             ansible_hostname == current_ers_node.stdout
      block:
        - name:                         "Test Execution: Find replication server PID"
          ansible.builtin.shell:        "pgrep -f 'er.sap{{ sap_sid }}'"
          register:                     er_pid
          changed_when:                 false

        - name:                         "Test Execution: Kill replication server process"
          ansible.builtin.command:      "kill -9 {{ er_pid.stdout }}"
          register:                     kill_result
          when:                         er_pid.stdout != ""

        - name:                         "Test Execution: Wait for process restart"
          ansible.builtin.wait_for:
            timeout:                    30

        - name:                         "Test Execution: Verify process restart"
          ansible.builtin.shell:        "pgrep -f 'er.sap{{ sap_sid }}'"
          register:                     new_er_pid
          changed_when:                 false
          retries:                      6
          delay:                        10
          until:                        new_er_pid.stdout != "" and new_er_pid.stdout != er_pid.stdout

    - name:                             "Test Execution: Stop timer"
      ansible.builtin.set_fact:
        test_execution_end:             "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

    - name:                             "Test Execution: Get final cluster status"
      ansible.builtin.command:          crm_mon -1 -o
      register:                         cluster_status_post
      changed_when:                     false

    - name:                             "Set test case message and details"
      ansible.builtin.set_fact:
        test_case_message_from_test_case: "Enqueue replication server process killed and auto-recovered on {{ current_ers_node.stdout }}"
        test_case_details_from_test_case: {
                                        "Pre Validations Status": "{{ cluster_status_pre.stdout }}",
                                        "Original PID": "{{ er_pid.stdout }}",
                                        "Kill Result": "{{ kill_result }}",
                                        "New PID": "{{ new_er_pid.stdout }}",
                                        "Post Status": "{{ cluster_status_post.stdout }}"
                                        }

# /*---------------------------------------------------------------------------
# |                          Post Validations                                 |
# +--------------------------------------------------------------------------*/
    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"

  rescue:
    - name:                             "Rescue operation"
      ansible.builtin.include_tasks:    "roles/misc/tasks/rescue.yml"
