# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------
# |                          Kill Enqueue Server Process                      |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup Tasks"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                                 "Pre Validations: Get initial cluster status"
  become:                               true
  ansible.builtin.command:              crm_mon -1 -o
  register:                             cluster_status_pre
  changed_when:                         false

- name:                                 "Pre Validations: Get current ASCS node"
  ansible.builtin.shell: |
                                        set -o pipefail
                                        crm resource status rsc_sap_{{ sap_sid }}_ASCS{{ scs_instance_number }} | \
                                        grep Started | awk '{print $4}'
  register:                             current_ascs_node
  changed_when:                         false

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Execution: Kill Enqueue Server Process"
  become:                               true
  when:                                 node_tier == "scs"
  block:
    - name:                             "Test Execution: Start timer"
      ansible.builtin.set_fact:
        test_execution_start:           "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

    - name:                             "Test Execution: Kill enqueue server on ASCS node"
      when:                             ansible_hostname == current_ascs_node.stdout
      block:
        - name:                         "Test Execution: Find enqueue server PID"
          ansible.builtin.shell:        "pgrep -f 'en.sap{{ sap_sid }}'"
          register:                     enq_pid
          changed_when:                 false

        - name:                         "Test Execution: Kill enqueue server process"
          ansible.builtin.command:      "kill -9 {{ enq_pid.stdout }}"
          register:                     kill_result
          when:                         enq_pid.stdout != ""

        - name:                         "Test Execution: Wait for failover"
          ansible.builtin.command:      "crm_mon -1"
          register:                     failover_status
          until:                        ("Started" in failover_status.stdout) and (current_ascs_node.stdout not in failover_status.stdout)
          retries:                      30
          delay:                        10

    - name:                             "Test Execution: Stop timer"
      ansible.builtin.set_fact:
        test_execution_end:             "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

    - name:                             "Test Execution: Get final cluster status"
      ansible.builtin.command:          crm_mon -1 -o
      register:                         cluster_status_post
      changed_when:                     false

    - name:                             "Set test case message and details"
      ansible.builtin.set_fact:
        test_case_message_from_test_case: "Enqueue server process killed and failed over successfully"
        test_case_details_from_test_case: {
                                        "Pre Validations Status": "{{ cluster_status_pre.stdout }}",
                                        "Original PID": "{{ enq_pid.stdout }}",
                                        "Kill Result": "{{ kill_result }}",
                                        "Failover Status": "{{ failover_status }}",
                                        "Post Status": "{{ cluster_status_post.stdout }}"
                                        }

# /*---------------------------------------------------------------------------
# |                          Post Validations                                 |
# +--------------------------------------------------------------------------*/
    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"

  rescue:
    - name:                             "Rescue operation"
      ansible.builtin.include_tasks:    "roles/misc/tasks/rescue.yml"
