---
##########################################################################################
#                   Task to get the cluster report from the primary instance             #
#                 after all the test cases have been executed.                           #
##########################################################################################
- name:                               Get the cluster status"
  become:                             true
  get_cluster_status:
    operation_step:                   "cluster_report_collection"
  register:                           cluster_status
  failed_when:                        cluster_status.primary_node == "" or cluster_status.secondary_node == ""

- name:                               "Get the cluster report from the primary node, copy it to localhost and remove the report from the primary node"
  become:                             true
  when:                               cluster_status is defined and cluster_status.primary_node == ansible_hostname
  block:
    - name:                           "Cluster report from the HA cluster"
      ansible.builtin.command:        "{{ commands | selectattr('name', 'equalto', 'crm_report_cmd') | map(attribute=(ansible_os_family | upper)) | first }}"
      register:                       cluster_report_results

    - name:                           "Copy the cluster report to the local machine"
      ansible.builtin.fetch:
        src:                          "/tmp/{{ test_group_invocation_id }}{% if ansible_os_family == 'RedHat' %}.tar.bz2{% elif ansible_os_family == 'SUSE' %}.tar.gz{% endif %}"
        dest:                         "{{ _workspace_directory }}/logs/"
        flat:                         yes
      changed_when:                   false

    - name:                           "Remove the cluster report from the primary node"
      ansible.builtin.file:
        state:                        absent
        path:                         "/tmp/{{ test_group_invocation_id }}{% if ansible_os_family == 'RedHat' %}.tar.bz2{% elif ansible_os_family == 'SUSE' %}.tar.gz{% endif %}"
