    - name:                            "Cluster report from the HA cluster"
      ansible.builtin.include_tasks:   "./roles/misc/tasks/cluster_report.yml"
      when:
        - test_group_name is defined