---
##########################################################################################
#                   Task to get the cluster report from the primary instance             #
#                 after all the test cases have been executed.                           #
##########################################################################################
- name:                               "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }} Get the cluster status"
  become:                             true
  get_cluster_status:
    operation_step:                   "cluster_report_collection"
    database_sid:                     "{{ db_sid | lower }}"
  register:                           cluster_status
  failed_when:                        cluster_status.primary_node == ""

- name:                               "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }} Get the cluster report from the primary node, copy it to localhost and remove the report from the primary node"
  become:                             true
  when:                               cluster_status is defined and cluster_status.primary_node == ansible_hostname
  block:
    - name:                           "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }} Cluster report from the HA cluster"
      ansible.builtin.command:        "{{ commands | selectattr('name', 'equalto', 'crm_report_cmd') | map(attribute=(ansible_os_family | upper)) | first }}"
      register:                       cluster_report_results

    - name:                           "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }} Copy the cluster report to the local machine"
      ansible.builtin.fetch:
        src:                          "/tmp/{{ test_group_invocation_id }}.{{ item }}"
        dest:                         "{{ _workspace_directory }}/logs/cluster_report/"
        flat:                         yes
      changed_when:                   false
      ignore_errors:                  true
      with_items:
        - "tar.bz2"
        - "tar.gz"

    - name:                           "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }} Remove the cluster report from the primary node"
      ansible.builtin.file:
        state:                        absent
        path:                         "/tmp/{{ test_group_invocation_id }}.{{ item }}"
      ignore_errors:                  true
      with_items:
        - "tar.bz2"
        - "tar.gz"
