---
##########################################################################################
#                       Task to setup telemetry information for each test case           #
##########################################################################################
- name:                               Ensure a list of package version is available for logging"
  ansible.builtin.package_facts:

- name:                               "Setup telemetry data for each test case"
  ansible.builtin.set_fact:
    test_case_name:                   "{{ item.name }}"
    test_case_description:            "{{ item.description }}"
    test_case_invocation_id:          "{{ lookup('pipe', 'uuidgen') }}"
    test_case_start_time_epoch:       "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
    test_case_status:                 "Starting"
    package_versions:                 "Pacemaker: {{ ansible_facts.packages['pacemaker'] | default('Not Found') }}
                                        Resource Agent: {{ ansible_facts.packages['resource-agents'] | default('Not Found') }}
                                        Fencing Agent: {{ ansible_facts.packages['fence-agents-azure-arm'] | default('Not Found') }}
                                        SAPHanaSR: {{ ansible_facts.packages['SAPHanaSR'] | default('Not Found') }}"
    test_case_details:                {}
    test_case_message:                "Test case execution started"
