---
##########################################################################################
#                       Task to setup telemetry information for each test case           #
##########################################################################################
- name:                               "{{ ansible_date_time.iso8601 }} Ensure a list of package version is available for logging"
  ansible.builtin.package_facts:

- name:                               "{{ ansible_date_time.iso8601 }} Create package dictionary for telemetry data"
  become:                             true
  get_package_list:
    package_facts_list:               "{{ ansible_facts.packages }}"
  register:                           packages_list

- name:                               "{{ ansible_date_time.iso8601 }} Setup telemetry data for each test case"
  ansible.builtin.set_fact:
    test_case_name:                   "{{ item.name }}"
    test_case_description:            "{{ item.description }}"
    test_case_invocation_id:          "{{ lookup('pipe', 'uuidgen') }}"
    test_case_start_time_epoch:       "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
    test_case_status:                 "Starting"
    package_versions:                 "{{ packages_list.packages_list }}"
    test_case_details:                {}
    test_case_message:                "Test case execution started"
