---
##########################################################################################
#                       Task to setup telemetry information for each test case           #
##########################################################################################

- name:                               "Setup telemetry data for each test case"
  ansible.builtin.set_fact:
    test_case_name:                   "{{ item.name }}"
    test_case_description:            "{{ item.description }}"
    test_case_invocation_id:          "{{ lookup('pipe', 'uuidgen') }}"
    test_case_start_time_epoch:       "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
    test_case_status:                 "Starting"
    package_versions:                 "{{ ansible_facts.packages | default('') }}"
    ansible_callbacks:
      profile_tasks:                  true
