# /*---------------------------------------------------------------------------
# |                                                                            |
# |                          HA Configuration Validation                       |
# |                                                                            |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup Tasks"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"

- name:                                 "Pre Validations: Validate parameters for the DB nodes"
  become:                               true
  become_user:                          root
  block:
    - name:                             "HA Configuration check for the DB nodes"
      get_pcmk_properties:
        action:                         get
        sid:                            "{{ db_sid | upper }}"
        instance_number:                "{{ db_instance_number }}"
        ansible_os_family:              "{{ ansible_os_family | upper }}"
      register:                         test_result

    - name:                             "Set the test case status to PASSED"
      ansible.builtin.set_fact:
        test_case_name:                 "{{ item.name }}: {{ virtual_host }}"
        test_case_status:               "{{ test_result.status }}"
        test_case_message:              "Test Case Passed"
        test_case_details:              "{{ test_result.msg }}"
  rescue:
    - name:                             "Test case failed"
      ansible.builtin.set_fact:
          test_case_name:               "{{ item.name }}: {{ virtual_host }}"
          test_case_status:             "FAILED"
          test_case_details:            "{{ test_result }}"
          test_case_message:            "{{ ansible_failed_result }}"

- name:                                 "Post Telemetry Data"
  ansible.builtin.include_tasks:        "roles/misc/tasks/post-telemetry-data.yml"
