# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------
# |                          HA Configuration Validation                       |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup Tasks"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"

- name:                                 "Ensure a list of package version is available for logging"
  no_log:                               true
  ansible.builtin.package_facts:

- name:                                 "Create package dictionary for telemetry data"
  become:                               true
  get_package_list:
    package_facts_list:                 "{{ ansible_facts.packages }}"
  register:                             packages_list

- name:                                 "Pre Validations: Validate parameters for the DB nodes"
  become:                               true
  become_user:                          root
  block:
    - name:                             "Pre Validation: Get SAPHanaSR Provider"
      become:                           true
      become_user:                      "{{ db_sid | lower }}"
      ansible.builtin.command:          "/usr/sbin/SAPHanaSR-manageProvider --show --provider=sushanasr"
      register:                         hanasr_command_output
      changed_when:                     false

    - name:                             "Pre Validation: Set SAPHanaSR Provider"
      when:                             hanasr_command_output.stdout != 0
      ansible.builtin.set_fact:
        saphanasr_provider:             "SAPHanaSR"

    - name:                             "Pre Validation: Set SAPHanaSR-angi Provider"
      when:                             hanasr_command_output.stdout == ""
      ansible.builtin.set_fact:
        saphanasr_provider:             "SAPHanaSR-angi"

    - name:                             "Retrieve Virtual Machine name"
      ansible.builtin.uri:
        url:                            http://169.254.169.254/metadata/instance?api-version=2021-02-01
        use_proxy:                      false
        headers:
          Metadata:                     true
      register:                         azure_instance_metadata

    - name:                             "HA Configuration check for the DB nodes"
      get_pcmk_properties_db:
        sid:                            "{{ db_sid | upper }}"
        instance_number:                "{{ db_instance_number }}"
        virtual_machine_name:           "{{ azure_instance_metadata.json.compute.name }}"
        fencing_mechanism:              "{{ database_cluster_type }}"
        os_version:                     "{{ ansible_distribution_version }}"
        pcmk_constants:                 "{{ lookup('file', 'constants.yaml') | from_yaml }}"
        saphanasr_provider:             "{{ saphanasr_provider }}"
      register:                         test_result

    - name:                             "Set the test case status to PASSED"
      ansible.builtin.set_fact:
        test_case_name:                 "{{ item.name }}: {{ virtual_host }}"
        test_case_status:               "{{ test_result.status }}"
        test_case_message:              "{{ test_result.message }}"
        test_case_details:              "{{ test_result.details }}"
        test_case_hostname:             "{{ virtual_host }}"
        package_versions:               "{{ packages_list.details }}"

  rescue:
    - name:                             "Test case failed"
      ansible.builtin.set_fact:
          test_case_name:               "{{ item.name }}: {{ virtual_host }}"
          test_case_status:             "FAILED"
          test_case_details:            "{{ test_result }}"
          test_case_message:            "{{ ansible_failed_result }}"
          test_case_hostname:           "{{ virtual_host }}"
          package_versions:             "{{ packages_list.details }}"

- name:                                 "Post Telemetry Data"
  ansible.builtin.include_tasks:        "roles/misc/tasks/post-telemetry-data.yml"
