name: trivy

on:
  pull_request:
    types: [ 'opened', 'reopened', 'synchronize' ]
  merge_group:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: 'trivy scan'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Run Trivy vulnerability scanner (file system)
      uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # 0.29.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        scan-ref: .
        format: 'sarif'
        scanners: 'vuln,secret,config'
        output: report-fs.sarif

    - name: Upload Trivy report (fs) GitHub Security
      uses: github/codeql-action/upload-sarif@9e8d0789d4a0fa9ceb6b1738f7e269594bdd67f0 # v3.28.9
      with:
        sarif_file: report-fs.sarif
        category: 'fs'
